In [ ]:
# Lab03 Numpy Basics

In [3]:
# NumPy Basics
import numpy as np

s = np.arange(12)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
import numpy as np

s = np.arange(12)
print(s)

# 3) Show the third element of s

print (s[2])


# Show the last element of s

print (s[-1])




[ 0  1  2  3  4  5  6  7  8  9 10 11]
2
11


In [8]:
import numpy as np

s = np.arange(12)
print(s)

# 3) Show the third to last element of s

print (s[2:])


# Show the third to seventh element of s

print (s[2:7])



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10 11]
[2 3 4 5 6]


In [14]:
import numpy as np

s = np.arange(12)
print(s)


# 4) Show the total of s
print (np.sum(s))


# Show the smallest value of s
print (np.min(s))

# Show the average value of s
print (np.mean(s))

# Show the smallest value of s
print (np.max(s))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
66
0
5.5
11


In [17]:
# 5) if array change values, will s change values too? why?
# show s values

arry = s
arry[1]= -1
print(s)
print(arry)


[ 0 -1  2  3  4  5  6  7  8  9 10 11]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [18]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
print(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [21]:
matrix = np.array(data)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# 6)Show the element of first row of second col of matrix

print (matrix[0,1])

# 6)Show the element of second row of first col of matrix

print (matrix[1,0])

2
4


In [32]:
print (matrix)
print ("--------")

# 7 )Show all elements of first row in matrix

print (matrix[0])
print ("--------")

#  Show all elements of second row in matrix

print (matrix[1])
print ("--------")

# Show all elements of last row in matrix


print (matrix[-1])
print ("--------")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[1 2 3]
--------
[4 5 6]
--------
[7 8 9]
--------


In [35]:
print (matrix)
print ("--------")

# 8) Show all elements of first col in matrix
print (matrix[:,0])
print ("--------")



# Show all elements of third col in matrix

print (matrix[:,1])
print ("--------")



# Show all elements of last col in matrix
print (matrix[:,-1])
print ("--------")



[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[1 4 7]
--------
[2 5 8]
--------
[3 6 9]
--------


In [36]:
print( matrix)
# Show second rows, and second col to last col's elements in matrix


print (matrix[1, 1:])
print ("--------")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]
--------


In [48]:
print(matrix)
print ("--------")


# 5) Show the total of s

print (sum(matrix))
print ("--------")


# Show the smallest value of s

print (matrix.min())
print (np.min(matrix))
print ("--------")


# Show the average value of s

print (matrix.mean())
print (np.mean(matrix))
print ("--------")


#show the largest values of matrix


print (matrix.max())
print (np.max(matrix))
print ("--------")



# The sum of second col
print(matrix [:,1].sum())
print (np.sum(matrix [:,1]))
print ("--------")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[12 15 18]
--------
1
1
--------
5.0
5.0
--------
9
9
--------
15
15
--------
